// ─────────────────────────────────────────────
//  50 NSE / BSE–style Indian Securities
// ─────────────────────────────────────────────
const SECURITIES = [
  { symbol: 'RELIANCE',   name: 'Reliance Industries',          price: 2450,  sector: 'Energy' },
  { symbol: 'TCS',        name: 'Tata Consultancy Services',     price: 3680,  sector: 'IT' },
  { symbol: 'INFY',       name: 'Infosys',                       price: 1520,  sector: 'IT' },
  { symbol: 'HDFCBANK',   name: 'HDFC Bank',                     price: 1640,  sector: 'Banking' },
  { symbol: 'ICICIBANK',  name: 'ICICI Bank',                    price: 960,   sector: 'Banking' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever',            price: 2380,  sector: 'FMCG' },
  { symbol: 'ITC',        name: 'ITC Limited',                   price: 430,   sector: 'FMCG' },
  { symbol: 'SBIN',       name: 'State Bank of India',           price: 780,   sector: 'Banking' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel',                 price: 1150,  sector: 'Telecom' },
  { symbol: 'KOTAKBANK',  name: 'Kotak Mahindra Bank',           price: 1820,  sector: 'Banking' },
  { symbol: 'LT',         name: 'Larsen & Toubro',               price: 3240,  sector: 'Infrastructure' },
  { symbol: 'AXISBANK',   name: 'Axis Bank',                     price: 1070,  sector: 'Banking' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints',                  price: 2890,  sector: 'Consumer' },
  { symbol: 'MARUTI',     name: 'Maruti Suzuki',                 price: 10450, sector: 'Auto' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance',                 price: 6720,  sector: 'Finance' },
  { symbol: 'HCLTECH',    name: 'HCL Technologies',              price: 1380,  sector: 'IT' },
  { symbol: 'TITAN',      name: 'Titan Company',                 price: 3290,  sector: 'Consumer' },
  { symbol: 'WIPRO',      name: 'Wipro',                         price: 540,   sector: 'IT' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement',              price: 9870,  sector: 'Cement' },
  { symbol: 'NESTLEIND',  name: 'Nestle India',                  price: 2240,  sector: 'FMCG' },
  { symbol: 'SUNPHARMA',  name: 'Sun Pharmaceuticals',           price: 1480,  sector: 'Pharma' },
  { symbol: 'ADANIENT',   name: 'Adani Enterprises',             price: 2560,  sector: 'Conglomerate' },
  { symbol: 'POWERGRID',  name: 'Power Grid Corporation',        price: 290,   sector: 'Utilities' },
  { symbol: 'NTPC',       name: 'NTPC Limited',                  price: 350,   sector: 'Utilities' },
  { symbol: 'ONGC',       name: 'Oil & Natural Gas Corp',        price: 230,   sector: 'Energy' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors',                   price: 820,   sector: 'Auto' },
  { symbol: 'TECHM',      name: 'Tech Mahindra',                 price: 1290,  sector: 'IT' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv',                 price: 1580,  sector: 'Finance' },
  { symbol: 'DRREDDY',    name: "Dr. Reddy's Laboratories",      price: 5680,  sector: 'Pharma' },
  { symbol: 'GRASIM',     name: 'Grasim Industries',             price: 2130,  sector: 'Cement' },
  { symbol: 'CIPLA',      name: 'Cipla',                         price: 1390,  sector: 'Pharma' },
  { symbol: 'DIVISLAB',   name: "Divi's Laboratories",           price: 3760,  sector: 'Pharma' },
  { symbol: 'EICHERMOT',  name: 'Eicher Motors',                 price: 4210,  sector: 'Auto' },
  { symbol: 'BPCL',       name: 'Bharat Petroleum Corp',         price: 380,   sector: 'Energy' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp',                 price: 4560,  sector: 'Auto' },
  { symbol: 'HINDALCO',   name: 'Hindalco Industries',           price: 590,   sector: 'Metals' },
  { symbol: 'JSWSTEEL',   name: 'JSW Steel',                     price: 850,   sector: 'Metals' },
  { symbol: 'MAHINDRA',   name: 'Mahindra & Mahindra',           price: 1920,  sector: 'Auto' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank',                 price: 1240,  sector: 'Banking' },
  { symbol: 'SBILIFE',    name: 'SBI Life Insurance',            price: 1450,  sector: 'Insurance' },
  { symbol: 'HDFCLIFE',   name: 'HDFC Life Insurance',           price: 680,   sector: 'Insurance' },
  { symbol: 'TATASTEEL',  name: 'Tata Steel',                    price: 140,   sector: 'Metals' },
  { symbol: 'COALINDIA',  name: 'Coal India',                    price: 420,   sector: 'Mining' },
  { symbol: 'UPL',        name: 'UPL Limited',                   price: 530,   sector: 'Agriculture' },
  { symbol: 'SHREECEM',   name: 'Shree Cement',                  price: 2640,  sector: 'Cement' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals',              price: 5670,  sector: 'Healthcare' },
  { symbol: 'BRITANNIA',  name: 'Britannia Industries',          price: 4780,  sector: 'FMCG' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries',           price: 2650,  sector: 'Consumer' },
  { symbol: 'SIEMENS',    name: 'Siemens India',                 price: 5240,  sector: 'Industrial' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products',        price: 1080,  sector: 'FMCG' },
];

// Helper: get a security by symbol
function getSecurityBySymbol(sym) {
  return SECURITIES.find(s => s.symbol === sym) || null;
}
